fix exclude-fmt-errorf and check-gomod jobs
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

diff --git a/.github/workflows/exclude-fmt-errorf.yaml b/.github/workflows/exclude-fmt-errorf.yaml
--- a/.github/workflows/exclude-fmt-errorf.yaml
+++ b/.github/workflows/exclude-fmt-errorf.yaml
@@ -1,17 +1,15 @@
 ---
-name: Check go.mod and go.sum
+name: Exclude fmt.Errorf
 on:
   workflow_call:
 jobs:
-  checkgomod:
+  exclude-fmt-errorf:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - uses: actions/setup-go@v1
-        with:
-          go-version: 1.18.1
-      - run: go mod tidy
-      - name: Check for changes in go.mod or go.sum
+      - name: Exclude fmt.Errorf
         run: |
-          git diff --name-only --exit-code go.mod || ( echo "Run go tidy" && false )
-          git diff --name-only --exit-code go.sum || ( echo "Run go tidy" && false )
+          if grep -r --include=*.go --exclude=*.pb.go fmt.Errorf . ; then
+           echo "Please use errors.Errorf (or errors.New or errors.Wrap or errors.Wrapf) as appropriate rather than fmt.Errorf"
+           exit 1
+          fi
